@startuml
'https://plantuml.com/class-diagram
class ListCreator{
 -String listTitle
 +HashMap item (String description, String dueDate)
 -getTitle
 -setTitle
 -createList()
}

class EditItems{
  -additem()
  -removeitem()
  -changeDescription()
  -changeDueDate()
}

class EditList{
    storeList()
    removeList()
    editListTitle()
}


@enduml